CREATE TYPE role_type AS ENUM ('ADMIN', 'USER');

CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL UNIQUE NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE role_type NOT NULL,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE IF NOT EXISTS USER_INFO (
    ID INT,
    NOME VARCHAR(255) NOT NULL,
    COGNOME VARCHAR(255) NOT NULL,
    INDIRIZZO VARCHAR(255),
    CAP VARCHAR(255),
    PROVINCIA VARCHAR(2),
    STATO VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE NUMERIC NOT NULL,
    STOCK_QUANTITY INT,
    IS_DELETED BOOLEAN DEFAULT FALSE
);

CREATE TYPE delivery_status_type AS ENUM ('PENDING', 'SHIPPED', 'DELIVERED');
CREATE TYPE payment_status_type AS ENUM ('PENDING', 'PAID', 'FAILED');

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    DELIVERY_STATUS delivery_status_type,
    PAYMENT_STATUS payment_status_type,
    FOREIGN KEY (USER_ID) REFERENCES USERS(id)
);

CREATE TABLE ORDERS_DETAILS (
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE
);